### ISSUE TITLE
MOC example request

### ISSUE THREAD

**Issue by EvanMath** [yoyurec/logseq-starter-graph#1]
Hey there,

Very good job with this starter graph. I really enjoyed it and didn't lose time trying different things instead I followed the other way, removing anything I don't need. I would like to ask if you could give some example of MOC templates and how to use it. It was the only one without an example to understand it. 

Thanks in advance!

**Comment by yoyurec** [comment]
MOC is just a page with structured links about one big topic (in opposite to classic PKM rule "link from bottom to top via backlinks")
![image](https://user-images.githubusercontent.com/137919/175136646-18b4abe9-7c17-4a17-9802-938e65e80be5.png)

You can also do _(already existing [[🌌 moc]] page in this Starter pack)_ MOC of MOCs )) - page with links to your MOCs for different life areas...
![image](https://user-images.githubusercontent.com/137919/175138208-226551a6-0965-4055-b78c-8c4c8015cd87.png)

I'm adding `type:: [[🌌 moc]]` to such pages, so I can build the Query to get all of them in table view (in case I don't want to organize them manually or just to see orphans) on special _[[🌌 moc]] page (included in this Starter pack)_.
![image](https://user-images.githubusercontent.com/137919/175138541-a29afd39-a131-49f3-aeb7-fb25083ff32c.png)

So in my setup i use the template "moc" for big topic pages, template adds the type"moc, I can click on it and go to MOCS of MOCs ( Index\Master MOC), and this page content consists of 2 parts: manually curated list + generated table.

A lot of videos on YouTube, for ex. this one - [Organizing Obsidian with Maps of Content (MOCs) - YouTube](https://www.youtube.com/watch?v=7GqQKCT0PZ4&t=6s)

**Comment by EvanMath** [comment]
Ok, great. Thank you for these clarifications.
